# this options will be accessable throught sfConfig::get with a name prefix: sf_phpunit_*

all:
  framework:
    autoload_script: '%SF_ROOT_DIR%/plugins/sfPhpunitPlugin/config/autoload_3.5.php'

  # project test directory
  dir:                   '%SF_TEST_DIR%/phpunit'
  
  arguments:

  # todo 
  fixture:
    doctrine:
    
    propel:
    
    dbunit:
  

  filter:
    vendor: {path: '%SF_LIB_DIR%/vendor', ext: '.php'}
    plugins: {path: '%SF_ROOT_DIR%/plugins', ext: '.php'}
    cache: {path: '%SF_ROOT_DIR%/cache', ext: '*'}
    log: {path: '%SF_ROOT_DIR%/log', ext: '*'}
    apps: {path: '%SF_ROOT_DIR%/apps', ext: '*'}
    models-base: {path: '%SF_LIB_DIR%/model/doctrine/base', ext: '*'}
    form-base: {path: '%SF_LIB_DIR%/form/doctrine/base', ext: '*'}
    filter-base: {path: '%SF_LIB_DIR%/filter/doctrine/base', ext: '*'}
    tests: {path: '%SF_ROOT_DIR%/test', ext: '.php'}
        
  amf:
    endpoint:            false
  
  mink:
    default_driver: 'goutte'
    drivers:
      goutte:
        zendConfig: [encodecookies: false] # zend config parameters
        serverParameters: [] # server parameters
      sahi:
        browser: 'firefox' # browser name to use
        sid: null # sahi SID
        host: 'localhost' # sahi proxy host
        port: 9999 # port number
      zombie:
        host: '127.0.0.1' # zombie.js server host
        port: 8124 # port number
        autoServer: true # use bundled with driver server or manually started one
        nodeBin: 'node' # path to node binary
      selenium:
        host: 'localhost' # selenium server server host
        port: '4444' # port number
        browser: 'firefox' # browser name to use
        baseUrl: '' # base URL
        timeout: 30 # time out in seconds
      webdriver:
        browser: 'firefox' #browser name
        host: 'http://localhost:4444/wd/hub' #selenium server server host
        desiredCapabilities: null #The desired capabilities
      
  
  selenium:
    collect_coverage: false
    
    remote_project_dir:
    #you can used it in case of the test application and selenium server are run on different computers.
    #but you have to upload the file stored in fixtures through web page.
    #You need to mount prj dir to selenium computer and define this option.
    #From the test case use for example method fixture()->getDirOwnAsRemote()
            
    driver:
      name:              false
      browser:           '*firefox'
      browser_url:       false
      host:              false
      port:              false
      timeout:           false
      http_timeout:      false
      sleep:             false
      wait:              false
  
  init:
    apps_test_index:     true
    base_classes:        true
    required_dirs:       true
    test_fixture_dirs:   true
